openapi: "3.0.2"
info:
  title: Stalker API
  version: "0.1.0"
  description: "Stalker API - GruppOne for Imola Informatica"
servers:
  - url: http://localhost:8080/
    description: Server localhost
tags:
  - name: blablabla
    description: blablabla
paths:
  /userAuthentication:
    post:
      description: faefeqf
      responses:
        "200":
          description: OK
components:
  schemas:
    # reference to User
    User:
      $ref: "./resources/user.yml"
    # reference to Organization
    Organization:
      $ref: "./resources/organization.yml"
    # reference to AppConnections
    AppConnections:
      $ref: "./resources/appConnections.yml"

    #TODO
    UserAccessToPlace:
      type: object
      properties:
        property:
          type: integer
    #TODO
    UserExitFromPlace:
      type: object
      properties:
        property:
          type: integer
