version: "3.7"

#################### THIS SECTIONS CONTAINS SOME EXPLANATIONS AND TIPS ON HOW TO WORK WITH DOCKER-COMPOSE ##############

# The environment variables (including passwords) required to configure our services are specified inside a .env file in the repository root directory. The .env

# Removed container_name properties because if they're set we cannot start multiple copies of the service

# The "ports" mapping exposes the given ports to the HOST. The "expose" mapping only exposes given the ports to other services, which is what we want because only the server talks to the external world

# We use named volumes short syntax: [SOURCE:]TARGET[:MODE].
# SOURCE is the named volume, TARGET is the folder inside the container MODE is ro (read-only),

# To get an interactive shell inside a RUNNING container, use:
# 'docker-compose exec <service-mapping-key> <shell-command>'
#
### EXAMPLES
#
# generic bash shell:
# docker-compose exec <...> bash
#
# MariaDB shell:
# docker-compose exec rdb mariadb
#
# InfluxDB shell:
# docker-compose exec tsdb influx

########################################################################################################################

# TODO how do i define a REQUIRED environment variable?
# TODO how do we define external services like our web-app?
# TODO use restart policy On-failure to restart container when stopped by errors?
# TODO https://docs.docker.com/compose/compose-file/#environment
services:
  # TODO add server container configuration
  # server:
  #   build: ...

  rdb:
    build:
      context: ./db/relational
      # # XXX we will use build: target: prod to specify the target stage with multi-stage dockerfiles
      # target: name-of-stage

      restart: unless-stopped

    environment:
      # empty values mean "get it from the .env file"
      MYSQL_DATABASE:
      MYSQL_ROOT_PASSWORD:

    # Opens port 3306 to the other services
    expose:
      - "3306"

    volumes:
      - ./db/relational/mysqldb:/var/lib/mysql

  tsdb:
    build:
      context: ./db/time-series
      # # XXX we will use build: target: prod to specify the target stage with multi-stage dockerfiles
      # target: name-of-stage

    restart: unless-stopped

    environment:
      # empty values mean "get it from the .env file"
      INFLUXDB_DB:
      INFLUXDB_ADMIN_USER:
      INFLUXDB_ADMIN_PASSWORD:

    # Opens port 8086 to the other services
    expose:
      - "8086"

    volumes:
      - .db/time-series/influxdb:/var/lib/influxdb/data

# TODO should use this on the left side of tsdb and rdb volumes syntax ([SOURCE:]TARGET[:MODE])
# Names our volumes
volumes:
  data-rdb:
  data-tsdb:
