version: "3.7"

# TODO remove this file to expose rdb and tsdb only to the stack's internal network
services:

  rdb:
    ports:
      - "3306:3306"

  rdb-gui:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - rdb

    environment:
      PMA_HOST: rdb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}

    ports:
      - "8080:80"

  tsdb:
    ports:
      - "8086:8086"

  tsdb-gui:
    image: chronograf:1.8-alpine
    depends_on:
      - tsdb

    environment:
      INFLUXDB_URL: http://tsdb:8086
      INFLUXDB_USERNAME: root
      INFLUXDB_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD:?err}

    ports:
      - "8888:8888"
