version: "3.7"

services:

  ldap-server:
    build:
      context: .

    restart: always

    environment:
      LDAP_ORGANISATION: Stalker test organization
      LDAP_DOMAIN: stalker.intern
      LDAP_ADMIN_PASSWORD: test1234
      LDAP_BASE_DN: dc=stalker,dc=intern

    expose:
      # for unsecure connection
      - "389"
      # for encrypted SSL connection
      - "636"

    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d

volumes:
  ldap-data:
  ldap-config:
