# The extension of this file needs to be ".yaml" and not ".yml"
openapi: "3.0.3"

info:
  title: Stalker API
  description: |
    The API specification developed by GruppOne for the Stalker project.

  contact:
    name: GruppOne
    email: gruppone.swe@gmail.com
    url: https://github.com/GruppOne

  license:
    name: GNU GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0-standalone.html

  version: "0.1.0"

servers:
  - url: http://localhost:8080
    description: Development server
  - url: https://{environment}.gruppone.tech/v{majorVersion}
    variables:
      environment:
        enum:
          # Production server
          - api
          # Staging server
          - api.staging
        default: api
      majorVersion:
        # TODO this needs to be managed by .release scripts
        default: "0"

tags:
  - name: stalker mobile app
    description: This operation should be available to mobile app users.
  - name: stalker web app
    description: This operation should be available to web app users (owners, managers, viewers).

# TODO define links https://swagger.io/docs/specification/links/ to reach the full glory of REST
# TODO explicitly declare permissions schema for admin roles
# TODO use plurals: /users, not /user
# TODO use http status 202 "accepted" for long async operations
paths:
  /location/update:
    post:
      tags:
        - stalker mobile app
      description: Send an update for an user's current location.
      operationId: postLocationUpdate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LocationInfo"
      responses:
        # TODO did i forget some responses?
        "200":
          $ref: "#/components/responses/Ok"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        default:
          $ref: "#/components/responses/DefaultResponse"

  /user/login:
    post:
      tags:
        - stalker mobile app
        - stalker web app
      description: Log in an existing user.
      operationId: loginUser
      # Disable security for this endpoint
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UnauthenticatedUser"
      responses:
        "200":
          description: Ok. returns the user's information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          $ref: "#/components/responses/Unauthorized"
        default:
          $ref: "#/components/responses/DefaultResponse"

  /user/{userId}/subscribed:
    parameters:
      - $ref: "#/components/parameters/userId"

    get:
      tags:
        - stalker mobile app
        - stalker web app
      description: Get the list of organizations that a user has connected to.
      operationId: getConnectedOrganizationsByUserId
      responses:
        "200":
          description: The list of the ids of the organizations the user is connected to.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GenericId"
        "404":
          $ref: "#/components/responses/NotFound"
        default:
          $ref: "#/components/responses/DefaultResponse"

  /organization:
    get:
      tags:
        - stalker mobile app
        - stalker web app
      description: Get the list of all the organizations registered to Stalker.
      operationId: getAllOrganizations
      responses:
        "200":
          description: The list of organizations registered to Stalker.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Organization"
        "404":
          $ref: "#/components/responses/NotFound"
        default:
          $ref: "#/components/responses/DefaultResponse"

  /organization/{organizationId}/place:
    parameters:
      - $ref: "#/components/parameters/organizationId"
    post:
      tags:
        - stalker web app
      description: Add a new place to the given organization. Operation reserved only to the managers and up.
      operationId: addPlaceIntoAnOrganizationById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Organization"
      responses:
        "200":
          description: Success, the place has been created.
        "400":
          description: The place already exists inside the current organization.
        "401":
          $ref: "#/components/responses/Unauthorized"
        default:
          $ref: "#/components/responses/DefaultResponse"

# Apply security scheme globally
security:
  - AdminKey: []

components:
  parameters:
    userId:
      in: path
      name: userId
      description: The id of an user.
      required: true
      schema:
        $ref: "#/components/schemas/GenericId"

    organizationId:
      in: path
      name: organizationId
      description: The id of an organization.
      required: true
      schema:
        $ref: "#/components/schemas/GenericId"

    placeId:
      in: path
      name: placeId
      description: The id of a place.
      required: true
      schema:
        $ref: "#/components/schemas/GenericId"

  # TODO reuse bodies?
  # requestBodies:

  # TODO add explicit json content to errors
  responses:
    # 200
    Ok:
      description: Ok.

    # 401
    Unauthorized:
      description: The user is not authenticated.

    # 403
    Forbidden:
      description: The user is authenticated but not authorized.

    # 404
    NotFound:
      description: The specified resource was not found

    # 500
    DefaultResponse:
      description: Unexpected error

    # 501
    NotImplemented:
      description: This endpoint has not been implemented yet.

  schemas:
    AppConnection:
      $ref: "./schemas/AppConnection.yaml#"

    GenericId:
      $ref: "./schemas/GenericId.yaml#"

    LocationInfo:
      $ref: "./schemas/LocationInfo.yaml#"

    Organization:
      $ref: "./schemas/Organization.yaml#"

    Place:
      $ref: "./schemas/Place.yaml#"

    PlaceData:
      $ref: "./schemas/PlaceData.yaml#"

    UnauthenticatedUser:
      $ref: "./schemas/UnauthenticatedUser.yaml#"

    User:
      $ref: "./schemas/User.yaml#"

  securitySchemes:
    AdminKey:
      type: apiKey
      in: header
      # name of the header
      name: STALKER-ADMIN-API-KEY
