name: Conventional Commits

on:
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # semantic-pr:
  #   name: Check PR title
  #   runs-on: ubuntu-18.04

  #   steps:
  #     - name: Run PR title checker
  #       uses: amannn/action-semantic-pull-request@v1.2.0

  commitsar:
    name: Check all commits
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Run commitsar
        uses: docker://aevea/commitsar:0.13.0
