name: Documentation jobs

on:
  pull_request:
    branches:
      - master
  # push:
  #   branches:
  #     - '!master'

# TODO add PlantUML job
# TODO add spellcheck job: https://github.com/marketplace/actions/spellcheck-action
jobs:
  # the idea was to run git status -s to verify that diagrams are up to date, so that no git commit/push is needed
  # plantuml:
  #   name: Generate PlantUML diagrams
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     # - name: PlantUML Action
  #     #   uses: Timmy/plantuml-action@v1
  #     #   with:
  #     #     args:

  lint-markdown:
    name: Lint markdown files
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          ignore_files: 'CHANGELOG.md'

  lint-api:
    name: Lint API definition
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Run spectral linter via npx
        run: npx --package @stoplight/spectral@~5.3.0 spectral lint ./api
