name: Project management

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

  # push:
  #   branches-ignore:
  #     - master

env:
  MY_GITHUB_TOKEN: ${{ secrets.ERCLU_ORGANIZATION_TOKEN }}

jobs:
  # FIXME nessuno di questi due job funziona
  # create-draft-pr:
  #   runs-on: ubuntu-latest

  #   if: github.event_name == 'push'

  #   steps:
  #     - uses: actions/checkout@v1

  #     - name: pull-request
  #       uses: repo-sync/pull-request@v2
  #       with:
  #         github_token: ${{ secrets.ERCLU_ORGANIZATION_TOKEN }}
  #         source_branch: ""
  #         destination_branch: "master"
  #         pr_title: "Pulling ${{ github.ref }} into master"
  #         pr_body: This PR was createad automatically. Modify appropriately its title and body.
  #         pr_draft: true

  # create-draft-pr-too:
  #   name: Create draft PR on new branch push
  #   runs-on: ubuntu-latest

  #   if: github.event_name == 'push'

  #   steps:
  #     - name: pull-request-action
  #       uses: vsoch/pull-request-action@1.0.5
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.ERCLU_ORGANIZATION_TOKEN }}
  #         PULL_REQUEST_BRANCH: miglioramenti-ci
  #         PULL_REQUEST_TITLE: Pulling ${{ github.ref }} into master
  #         PULL_REQUEST_BODY: This PR was createad automatically. Modify appropriately its title and body.
  #         PULL_REQUEST_DRAFT: true

  assign-main-project:
    name: Assign to our main project board
    runs-on: ubuntu-18.04

    # if: github.event_name != 'push'

    steps:
      - name: Assign new issues and new PRs to the main organization project board
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: github.event.action == 'opened' && !contains(github.event.issue.labels.*.name, 'requirement')
        with:
          project: "https://github.com/orgs/GruppOne/projects/9"
          column_name: "To do"

  assign-requirement-main-project:
    name: Assign a requirement to our main project board
    runs-on: ubuntu-18.04

    # if: github.event_name != 'push'

    steps:
      - name: Assign new requirement to the correct project column
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: contains(github.event.issue.labels.*.name, 'requirement')
        with:
          project: "https://github.com/orgs/GruppOne/projects/9"
          column_name: "To do - Requirements"
