name: Scan master and upload to SonarCloud

on:
  push:
    branches:
      - master

jobs:
  sonarcloud-master-scanner:
    name: Fully scan master with SonarCloud
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Gradle wrapper
        run: ./gradlew --console=plain --warning-mode=all --info

      - name: Run gradle check
        run: ./gradlew --console=plain --warning-mode=all --info --continue check

      - name: Run SonarCloud scanner task
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
        # exclude dependent tasks that were already executed during "Run gradle check" step
        run: |
          ./gradlew \
            --console=plain \
            --warning-mode=all \
            --info \
            sonarqube \
            -x test \
            -Dsonar.login=${{ secrets.SONARCLOUD_LOGIN }}
