# name: Static code analysis

# on:
#   pull_request:
#     branches:
#       - master

# jobs:
#   lint:
#     name: Lint Java code
#     runs-on: ubuntu-18.04

#     steps:
#       - uses: actions/checkout@v2
