
name: Static code analysis

on:
  pull_request:
  # push:
  #   branches:
  #     - '!master'

jobs:

  lint:
    name: Lint API definition
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Run spectral linter via npx
        run: npx spectral lint ./api/**.yaml
